---

<a href='http://www.pieriandata.com'><img src='../Pierian_Data_Logo.png'/></a>

---

<center><em>Авторские права принадлежат Pierian Data Inc.</em></center>
<center><em>Для дополнительной информации посетите наш сайт <a href='http://www.pieriandata.com'>www.pieriandata.com</a></em></center>

# Операции группировки данных (Groupby) и многоуровневый индекс (мульти-индекс)

In [1]:
import numpy as np
import pandas as pd

## Данные

In [2]:
df = pd.read_csv('mpg.csv')

In [3]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

## Метод groupby()

In [4]:
# Создаёт объект groupby, который ожидает метода агрегации
df.groupby('model_year')

#### Добавляем вызов метода агрегации. Чтобы использовать объект groupby, нам нужно сообщить pandas, как мы хотим агрегировать данные.

Наиболее частые варианты:

    mean(): среднее значение
    sum(): сумма значений
    size(): размер группы
    count(): количество элементов
    std(): среднеквадратичное отклонение (standard deviation)
    var(): дисперсия (variance)
    sem(): стандартная ошибка среднего (standard error of the mean)
    describe(): суммарные статистики
    first(): первое значение
    last(): последнее значение
    nth() : n-ое значение, или набор значений если n является списком
    min(): минимальное значение
    max(): максимальное значение

Полный список функций можно посмотреть в документации: https://pandas.pydata.org/docs/reference/groupby.html

In [ ]:
# Колонка model_year становится индексом! Теперь это НЕ название колонки, а название индекса

# ВНИМАНИЕ! В будущих версиях Scikit-Learn нужно добавлять параметр numeric_only=True
#
# df.groupby('model_year').mean(numeric_only=True)

df.groupby('model_year').mean()

,mpg,cylinders,displacement,weight,acceleration,origin
model_year,,,,,,
70,17.689655,6.758621,281.413793,3372.793103,12.948276,1.310345
71,21.250000,5.571429,209.750000,2995.428571,15.142857,1.428571
72,18.714286,5.821429,218.375000,3237.714286,15.125000,1.535714
73,17.100000,6.375000,256.875000,3419.025000,14.312500,1.375000
74,22.703704,5.259259,171.740741,2877.925926,16.203704,1.666667
75,20.266667,5.600000,205.533333,3176.800000,16.050000,1.466667
76,21.573529,5.647059,197.794118,3078.735294,15.941176,1.470588
77,23.375000,5.464286,191.392857,2997.357143,15.435714,1.571429
78,24.061111,5.361111,177.805556,2861.805556,15.805556,1.611111
79,25.093103,5.827586,206.689655,3055.344828,15.813793,1.275862
80,33.696552,4.137931,115.827586,2436.655172,16.934483,2.206897
81,30.334483,4.620690,135.310345,2522.931034,16.306897,1.965517
82,31.709677,4.193548,128.870968,2453.548387,16.638710,1.645161

In [ ]:
# ВНИМАНИЕ! В будущих версиях Scikit-Learn нужно добавлять параметр numeric_only=True
#
# avg_year = df.groupby('model_year').mean(numeric_only=True)

avg_year = df.groupby('model_year').mean()

TypeError: agg function failed [how->mean,dtype->object]

In [7]:
avg_year.index

Int64Index([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82], dtype='int64', name='model_year')

In [8]:
avg_year.columns

Index(['mpg', 'cylinders', 'displacement', 'weight', 'acceleration', 'origin'], dtype='object')

In [9]:
avg_year['mpg']

model_year
70    17.689655
71    21.250000
72    18.714286
73    17.100000
74    22.703704
75    20.266667
76    21.573529
77    23.375000
78    24.061111
79    25.093103
80    33.696552
81    30.334483
82    31.709677
Name: mpg, dtype: float64

In [ ]:
# ВНИМАНИЕ! В будущих версиях Scikit-Learn нужно добавлять параметр numeric_only=True
#
# df.groupby('model_year').mean(numeric_only=True)['mpg']

df.groupby('model_year').mean()['mpg']

model_year
70    17.689655
71    21.250000
72    18.714286
73    17.100000
74    22.703704
75    20.266667
76    21.573529
77    23.375000
78    24.061111
79    25.093103
80    33.696552
81    30.334483
82    31.709677
Name: mpg, dtype: float64

In [11]:
df.groupby('model_year').describe()

             mpg                                                          \
           count       mean       std   min     25%    50%     75%   max
model_year
70          29.0  17.689655  5.339231   9.0  14.000  16.00  22.000  27.0
71          28.0  21.250000  6.591942  12.0  15.500  19.00  27.000  35.0
72          28.0  18.714286  5.435529  11.0  13.750  18.50  23.000  28.0
73          40.0  17.100000  4.700245  11.0  13.000  16.00  20.000  29.0
74          27.0  22.703704  6.420010  13.0  16.000  24.00  27.000  32.0
75          30.0  20.266667  4.940566  13.0  16.000  19.50  23.000  33.0
76          34.0  21.573529  5.889297  13.0  16.750  21.00  26.375  33.0
77          28.0  23.375000  6.675862  15.0  17.375  21.75  30.000  36.0
78          36.0  24.061111  6.898044  16.2  19.350  20.70  28.000  43.1
79          29.0  25.093103  6.794217  15.5  19.200  23.90  31.800  37.3
80          29.0  33.696552  7.037983  19.1  29.800  32.70  38.100  46.6
81          29.0  30.334483  5.591465  17.6  26.600  31.60  34.400  39.1
82          31.0  31.709677  5.392548  22.0  27.000  32.00  36.000  44.0

           cylinders            ... acceleration       origin            \
               count      mean  ...          75%   max  count      mean
model_year                      ...
70              29.0  6.758621  ...       15.000  20.5   29.0  1.310345
71              28.0  5.571429  ...       16.125  20.5   28.0  1.428571
72              28.0  5.821429  ...       16.625  23.5   28.0  1.535714
73              40.0  6.375000  ...       16.000  21.0   40.0  1.375000
74              27.0  5.259259  ...       17.000  21.0   27.0  1.666667
75              30.0  5.600000  ...       17.375  21.0   30.0  1.466667
76              34.0  5.647059  ...       17.550  22.2   34.0  1.470588
77              28.0  5.464286  ...       16.925  19.0   28.0  1.571429
78              36.0  5.361111  ...       16.825  21.5   36.0  1.611111
79              29.0  5.827586  ...       17.300  24.8   29.0  1.275862
80              29.0  4.137931  ...       18.700  23.7   29.0  2.206897
81              29.0  4.620690  ...       17.300  20.7   29.0  1.965517
82              31.0  4.193548  ...       18.000  24.6   31.0  1.645161


                 std  min  25%  50%  75%  max
model_year
70          0.603765  1.0  1.0  1.0  1.0  3.0
71          0.741798  1.0  1.0  1.0  2.0  3.0
72          0.792658  1.0  1.0  1.0  2.0  3.0
73          0.667467  1.0  1.0  1.0  2.0  3.0
74          0.832050  1.0  1.0  1.0  2.0  3.0
75          0.730297  1.0  1.0  1.0  2.0  3.0
76          0.706476  1.0  1.0  1.0  2.0  3.0
77          0.835711  1.0  1.0  1.0  2.0  3.0
78          0.837608  1.0  1.0  1.0  2.0  3.0
79          0.591400  1.0  1.0  1.0  1.0  3.0
80          0.818505  1.0  2.0  2.0  3.0  3.0
81          0.944259  1.0  1.0  2.0  3.0  3.0
82          0.914636  1.0  1.0  1.0  3.0  3.0

[13 rows x 48 columns]

In [12]:
df.groupby('model_year').describe().transpose()

model_year                   70           71           72           73  \
mpg          count    29.000000    28.000000    28.000000    40.000000
             mean     17.689655    21.250000    18.714286    17.100000
             std       5.339231     6.591942     5.435529     4.700245
             min       9.000000    12.000000    11.000000    11.000000
             25%      14.000000    15.500000    13.750000    13.000000
             50%      16.000000    19.000000    18.500000    16.000000
             75%      22.000000    27.000000    23.000000    20.000000
             max      27.000000    35.000000    28.000000    29.000000
cylinders    count    29.000000    28.000000    28.000000    40.000000
             mean      6.758621     5.571429     5.821429     6.375000
             std       1.724926     1.665079     2.073708     1.807215
             min       4.000000     4.000000     3.000000     3.000000
             25%       6.000000     4.000000     4.000000     4.000000
             50%       8.000000     6.000000     4.000000     7.000000
             75%       8.000000     6.500000     8.000000     8.000000
             max       8.000000     8.000000     8.000000     8.000000
displacement count    29.000000    28.000000    28.000000    40.000000
             mean    281.413793   209.750000   218.375000   256.875000
             std     124.421380   115.102410   123.781964   121.722085
             min      97.000000    71.000000    70.000000    68.000000
             25%     198.000000    97.750000   109.250000   121.750000
             50%     307.000000   228.500000   131.000000   276.000000
             75%     383.000000   273.000000   326.000000   350.250000
             max     455.000000   400.000000   429.000000   455.000000
weight       count    29.000000    28.000000    28.000000    40.000000
             mean   3372.793103  2995.428571  3237.714286  3419.025000
             std     852.868663  1061.830859   974.520960   974.809133
             min    1835.000000  1613.000000  2100.000000  1867.000000
             25%    2648.000000  2110.750000  2285.500000  2554.500000
             50%    3449.000000  2798.000000  2956.000000  3338.500000
             75%    4312.000000  3603.250000  4169.750000  4247.250000
             max    4732.000000  5140.000000  4633.000000  4997.000000
acceleration count    29.000000    28.000000    28.000000    40.000000
             mean     12.948276    15.142857    15.125000    14.312500
             std       3.330982     2.666171     2.850032     2.754222
             min       8.000000    11.500000    11.000000     9.500000
             25%      10.000000    13.375000    13.375000    12.500000
             50%      12.500000    14.500000    14.500000    14.000000
             75%      15.000000    16.125000    16.625000    16.000000
             max      20.500000    20.500000    23.500000    21.000000
origin       count    29.000000    28.000000    28.000000    40.000000
             mean      1.310345     1.428571     1.535714     1.375000
             std       0.603765     0.741798     0.792658     0.667467
             min       1.000000     1.000000     1.000000     1.000000
             25%       1.000000     1.000000     1.000000     1.000000
             50%       1.000000     1.000000     1.000000     1.000000
             75%       1.000000     2.000000     2.000000     2.000000
             max       3.000000     3.000000     3.000000     3.000000

model_year                   74           75           76           77  \
mpg          count    27.000000    30.000000    34.000000    28.000000
             mean     22.703704    20.266667    21.573529    23.375000
             std       6.420010     4.940566     5.889297     6.675862
             min      13.000000    13.000000    13.000000    15.000000
             25%      16.000000    16.000000    16.750000    17.375000
             50%      24.000000    19.500000    21.000000    21.750000
             75%      27.000000    23.000000    26.375000    30.000000
             max      32.000000    33.000000    33.000000    36.000000
cylinders    count    27.000000    30.000000    34.000000    28.000000
             mean      5.259259     5.600000     5.647059     5.464286
             std       1.583390     1.522249     1.667558     1.815206
             min       4.000000     4.000000     4.000000     3.000000
             25%       4.000000     4.000000     4.000000     4.000000
             50%       4.000000     6.000000     6.000000     4.000000
             75%       6.000000     6.000000     7.500000     8.000000
             max       8.000000     8.000000     8.000000     8.000000
displacement count    27.000000    30.000000    34.000000    28.000000
             mean    171.740741   205.533333   197.794118   191.392857
             std      92.601127    87.669730    94.422256   107.813742
             min      71.000000    90.000000    85.000000    79.000000
             25%      90.000000   121.000000   102.500000    97.750000
             50%     122.000000   228.000000   184.000000   143.000000
             75%     250.000000   250.000000   291.000000   270.500000
             max     350.000000   400.000000   351.000000   400.000000
weight       count    27.000000    30.000000    34.000000    28.000000
             mean   2877.925926  3176.800000  3078.735294  2997.357143
             std     949.308571   765.179781   821.371481   912.825902
             min    1649.000000  1795.000000  1795.000000  1825.000000
             25%    2116.500000  2676.750000  2228.750000  2135.000000
             50%    2489.000000  3098.500000  3171.500000  2747.500000
             75%    3622.500000  3662.250000  3803.750000  3925.000000
             max    4699.000000  4668.000000  4380.000000  4335.000000
acceleration count    27.000000    30.000000    34.000000    28.000000
             mean     16.203704    16.050000    15.941176    15.435714
             std       1.688532     2.471737     2.801419     2.273391
             min      13.500000    11.500000    12.000000    11.100000
             25%      15.250000    14.125000    13.925000    14.000000
             50%      16.000000    16.000000    15.500000    15.650000
             75%      17.000000    17.375000    17.550000    16.925000
             max      21.000000    21.000000    22.200000    19.000000
origin       count    27.000000    30.000000    34.000000    28.000000
             mean      1.666667     1.466667     1.470588     1.571429
             std       0.832050     0.730297     0.706476     0.835711
             min       1.000000     1.000000     1.000000     1.000000
             25%       1.000000     1.000000     1.000000     1.000000
             50%       1.000000     1.000000     1.000000     1.000000
             75%       2.000000     2.000000     2.000000     2.000000
             max       3.000000     3.000000     3.000000     3.000000

model_year                   78           79           80           81  \
mpg          count    36.000000    29.000000    29.000000    29.000000
             mean     24.061111    25.093103    33.696552    30.334483
             std       6.898044     6.794217     7.037983     5.591465
             min      16.200000    15.500000    19.100000    17.600000
             25%      19.350000    19.200000    29.800000    26.600000
             50%      20.700000    23.900000    32.700000    31.600000
             75%      28.000000    31.800000    38.100000    34.400000
             max      43.100000    37.300000    46.600000    39.100000
cylinders    count    36.000000    29.000000    29.000000    29.000000
             mean      5.361111     5.827586     4.137931     4.620690
             std       1.495761     1.774199     0.580895     1.082781
             min       4.000000     4.000000     3.000000     4.000000
             25%       4.000000     4.000000     4.000000     4.000000
             50%       5.500000     6.000000     4.000000     4.000000
             75%       6.000000     8.000000     4.000000     6.000000
             max       8.000000     8.000000     6.000000     8.000000
displacement count    36.000000    29.000000    29.000000    29.000000
             mean    177.805556   206.689655   115.827586   135.310345
             std      76.012713    96.307581    33.744914    58.387929
             min      78.000000    85.000000    70.000000    79.000000
             25%     115.500000   121.000000    90.000000    98.000000
             50%     159.500000   183.000000   107.000000   119.000000
             75%     231.000000   302.000000   140.000000   151.000000
             max     318.000000   360.000000   225.000000   350.000000
weight       count    36.000000    29.000000    29.000000    29.000000
             mean   2861.805556  3055.344828  2436.655172  2522.931034
             std     626.023907   747.881497   432.235491   533.600501
             min    1800.000000  1915.000000  1835.000000  1755.000000
             25%    2282.500000  2556.000000  2110.000000  2065.000000
             50%    2910.000000  3190.000000  2335.000000  2385.000000
             75%    3410.000000  3725.000000  2800.000000  2900.000000
             max    4080.000000  4360.000000  3381.000000  3725.000000
acceleration count    36.000000    29.000000    29.000000    29.000000
             mean     15.805556    15.813793    16.934483    16.306897
             std       2.129915     2.952931     2.826694     2.192509
             min      11.200000    11.300000    11.400000    12.600000
             25%      14.475000    14.000000    15.100000    14.800000
             50%      15.750000    15.000000    16.500000    16.200000
             75%      16.825000    17.300000    18.700000    17.300000
             max      21.500000    24.800000    23.700000    20.700000
origin       count    36.000000    29.000000    29.000000    29.000000
             mean      1.611111     1.275862     2.206897     1.965517
             std       0.837608     0.591400     0.818505     0.944259
             min       1.000000     1.000000     1.000000     1.000000
             25%       1.000000     1.000000     2.000000     1.000000
             50%       1.000000     1.000000     2.000000     2.000000
             75%       2.000000     1.000000     3.000000     3.000000
             max       3.000000     3.000000     3.000000     3.000000

model_year                   82
mpg          count    31.000000
             mean     31.709677
             std       5.392548
             min      22.000000
             25%      27.000000
             50%      32.000000
             75%      36.000000
             max      44.000000
cylinders    count    31.000000
             mean      4.193548
             std       0.601074
             min       4.000000
             25%       4.000000
             50%       4.000000
             75%       4.000000
             max       6.000000
displacement count    31.000000
             mean    128.870968
             std      39.352037
             min      91.000000
             25%     105.000000
             50%     119.000000
             75%     142.000000
             max     262.000000
weight       count    31.000000
             mean   2453.548387
             std     354.276713
             min    1965.000000
             25%    2127.500000
             50%    2525.000000
             75%    2727.500000
             max    3035.000000
acceleration count    31.000000
             mean     16.638710
             std       2.484844
             min      11.600000
             25%      14.850000
             50%      16.400000
             75%      18.000000
             max      24.600000
origin       count    31.000000
             mean      1.645161
             std       0.914636
             min       1.000000
             25%       1.000000
             50%       1.000000
             75%       3.000000
             max       3.000000

## Groupby по нескольким колонкам

Давайте изучим средние значения по годам и по количеству цилиндров

In [ ]:
# ВНИМАНИЕ! В будущих версиях Scikit-Learn нужно добавлять параметр numeric_only=True
#
# df.groupby(['model_year','cylinders']).mean(numeric_only=True)

df.groupby(['model_year', 'cylinders']).mean()

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
71         4          27.461538    101.846154  2056.384615     16.961538
           6          18.000000    243.375000  3171.875000     14.750000
           8          13.428571    371.714286  4537.714286     12.214286
72         3          19.000000     70.000000  2330.000000     13.500000
           4          23.428571    111.535714  2382.642857     17.214286
           8          13.615385    344.846154  4228.384615     13.000000
73         3          18.000000     70.000000  2124.000000     13.500000
           4          22.727273    109.272727  2338.090909     17.136364
           6          19.000000    212.250000  2917.125000     15.687500
           8          13.200000    365.250000  4279.050000     12.250000
74         4          27.800000     96.533333  2151.466667     16.400000
           6          17.857143    230.428571  3320.000000     16.857143
           8          14.200000    315.200000  4438.400000     14.700000
75         4          25.250000    114.833333  2489.250000     15.833333
           6          17.583333    233.750000  3398.333333     17.708333
           8          15.666667    330.500000  4108.833333     13.166667
76         4          26.766667    106.333333  2306.600000     16.866667
           6          20.000000    221.400000  3349.600000     17.000000
           8          14.666667    324.000000  4064.666667     13.222222
77         3          21.500000     80.000000  2720.000000     13.500000
           4          29.107143    106.500000  2205.071429     16.064286
           6          19.500000    220.400000  3383.000000     16.900000
           8          16.000000    335.750000  4177.500000     13.662500
78         4          29.576471    112.117647  2296.764706     16.282353
           5          20.300000    131.000000  2830.000000     15.900000
           6          19.066667    213.250000  3314.166667     16.391667
           8          19.050000    300.833333  3563.333333     13.266667
79         4          31.525000    113.583333  2357.583333     15.991667
           5          25.400000    183.000000  3530.000000     20.100000
           6          22.950000    205.666667  3025.833333     15.433333
           8          18.630000    321.400000  3862.900000     15.400000
80         3          23.700000     70.000000  2420.000000     12.500000
           4          34.612000    111.000000  2360.080000     17.144000
           5          36.400000    121.000000  2950.000000     19.900000
           6          25.900000    196.500000  3145.500000     15.050000
81         4          32.814286    108.857143  2275.476190     16.466667
           6          23.428571    184.000000  3093.571429     15.442857
           8          26.600000    350.000000  3725.000000     19.000000
82         4          32.071429    118.571429  2402.321429     16.703571
           6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
           8          1.000000
71         4          1.923077
           6          1.000000
           8          1.000000
72         3          3.000000
           4          1.928571
           8          1.000000
73         3          3.000000
           4          2.000000
           6          1.250000
           8          1.000000
74         4          2.200000
           6          1.000000
           8          1.000000
75         4          2.166667
           6          1.000000
           8          1.000000
76         4          1.866667
           6          1.300000
           8          1.000000
77         3          3.000000
           4          1.857143
           6          1.400000
           8          1.000000
78         4          2.117647
           5          2.000000
           6          1.166667
           8          1.000000
79         4          1.583333
           5          2.000000
           6          1.000000
           8          1.000000
80         3          3.000000
           4          2.200000
           5          2.000000
           6          2.000000
81         4          2.095238
           6          1.714286
           8          1.000000
82         4          1.714286
           6          1.000000

In [ ]:
# ВНИМАНИЕ! В будущих версиях Scikit-Learn нужно добавлять параметр numeric_only=True
#
# df.groupby(['model_year','cylinders']).mean(numeric_only=True).index

df.groupby(['model_year', 'cylinders']).mean().index

MultiIndex([(70, 4),
            (70, 6),
            (70, 8),
            (71, 4),
            (71, 6),
            (71, 8),
            (72, 3),
            (72, 4),
            (72, 8),
            (73, 3),
            (73, 4),
            (73, 6),
            (73, 8),
            (74, 4),
            (74, 6),
            (74, 8),
            (75, 4),
            (75, 6),
            (75, 8),
            (76, 4),
            (76, 6),
            (76, 8),
            (77, 3),
            (77, 4),
            (77, 6),
            (77, 8),
            (78, 4),
            (78, 5),
            (78, 6),
            (78, 8),
            (79, 4),
            (79, 5),
            (79, 6),
            (79, 8),
            (80, 3),
            (80, 4),
            (80, 5),
            (80, 6),
            (81, 4),
            (81, 6),
            (81, 8),
            (82, 4),
            (82, 6)],
           names=['model_year', 'cylinders'])

# Мульти-индекс (MultiIndex)

## Объект MultiIndex

In [ ]:
# ВНИМАНИЕ! В будущих версиях Scikit-Learn нужно добавлять параметр numeric_only=True
#
# year_cyl = df.groupby(['model_year','cylinders']).mean()

year_cyl = df.groupby(['model_year', 'cylinders']).mean(numeric_only=True)

In [16]:
year_cyl

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
71         4          27.461538    101.846154  2056.384615     16.961538
           6          18.000000    243.375000  3171.875000     14.750000
           8          13.428571    371.714286  4537.714286     12.214286
72         3          19.000000     70.000000  2330.000000     13.500000
           4          23.428571    111.535714  2382.642857     17.214286
           8          13.615385    344.846154  4228.384615     13.000000
73         3          18.000000     70.000000  2124.000000     13.500000
           4          22.727273    109.272727  2338.090909     17.136364
           6          19.000000    212.250000  2917.125000     15.687500
           8          13.200000    365.250000  4279.050000     12.250000
74         4          27.800000     96.533333  2151.466667     16.400000
           6          17.857143    230.428571  3320.000000     16.857143
           8          14.200000    315.200000  4438.400000     14.700000
75         4          25.250000    114.833333  2489.250000     15.833333
           6          17.583333    233.750000  3398.333333     17.708333
           8          15.666667    330.500000  4108.833333     13.166667
76         4          26.766667    106.333333  2306.600000     16.866667
           6          20.000000    221.400000  3349.600000     17.000000
           8          14.666667    324.000000  4064.666667     13.222222
77         3          21.500000     80.000000  2720.000000     13.500000
           4          29.107143    106.500000  2205.071429     16.064286
           6          19.500000    220.400000  3383.000000     16.900000
           8          16.000000    335.750000  4177.500000     13.662500
78         4          29.576471    112.117647  2296.764706     16.282353
           5          20.300000    131.000000  2830.000000     15.900000
           6          19.066667    213.250000  3314.166667     16.391667
           8          19.050000    300.833333  3563.333333     13.266667
79         4          31.525000    113.583333  2357.583333     15.991667
           5          25.400000    183.000000  3530.000000     20.100000
           6          22.950000    205.666667  3025.833333     15.433333
           8          18.630000    321.400000  3862.900000     15.400000
80         3          23.700000     70.000000  2420.000000     12.500000
           4          34.612000    111.000000  2360.080000     17.144000
           5          36.400000    121.000000  2950.000000     19.900000
           6          25.900000    196.500000  3145.500000     15.050000
81         4          32.814286    108.857143  2275.476190     16.466667
           6          23.428571    184.000000  3093.571429     15.442857
           8          26.600000    350.000000  3725.000000     19.000000
82         4          32.071429    118.571429  2402.321429     16.703571
           6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
           8          1.000000
71         4          1.923077
           6          1.000000
           8          1.000000
72         3          3.000000
           4          1.928571
           8          1.000000
73         3          3.000000
           4          2.000000
           6          1.250000
           8          1.000000
74         4          2.200000
           6          1.000000
           8          1.000000
75         4          2.166667
           6          1.000000
           8          1.000000
76         4          1.866667
           6          1.300000
           8          1.000000
77         3          3.000000
           4          1.857143
           6          1.400000
           8          1.000000
78         4          2.117647
           5          2.000000
           6          1.166667
           8          1.000000
79         4          1.583333
           5          2.000000
           6          1.000000
           8          1.000000
80         3          3.000000
           4          2.200000
           5          2.000000
           6          2.000000
81         4          2.095238
           6          1.714286
           8          1.000000
82         4          1.714286
           6          1.000000

In [17]:
year_cyl.index

MultiIndex([(70, 4),
            (70, 6),
            (70, 8),
            (71, 4),
            (71, 6),
            (71, 8),
            (72, 3),
            (72, 4),
            (72, 8),
            (73, 3),
            (73, 4),
            (73, 6),
            (73, 8),
            (74, 4),
            (74, 6),
            (74, 8),
            (75, 4),
            (75, 6),
            (75, 8),
            (76, 4),
            (76, 6),
            (76, 8),
            (77, 3),
            (77, 4),
            (77, 6),
            (77, 8),
            (78, 4),
            (78, 5),
            (78, 6),
            (78, 8),
            (79, 4),
            (79, 5),
            (79, 6),
            (79, 8),
            (80, 3),
            (80, 4),
            (80, 5),
            (80, 6),
            (81, 4),
            (81, 6),
            (81, 8),
            (82, 4),
            (82, 6)],
           names=['model_year', 'cylinders'])

In [18]:
year_cyl.index.levels

FrozenList([[70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82], [3, 4, 5, 6, 8]])

In [19]:
year_cyl.index.names

FrozenList(['model_year', 'cylinders'])

In [ ]:
# тесты с индексом
# year_cyl.loc[70:77] # можно выбирать срезы по первому индексу
idx = pd.IndexSlice
# таким способом возьмём нужные из мультииндекса и все стобцы
year_cyl.loc[idx[70:77, 3:5], :]
# таким способом возьмём нужные из мультииндекса и все стобцы
year_cyl.loc[idx[70:77, 3:5], 'mpg':'weight']

                            mpg  displacement       weight
model_year cylinders
70         4          25.285714    107.000000  2292.571429
71         4          27.461538    101.846154  2056.384615
72         3          19.000000     70.000000  2330.000000
           4          23.428571    111.535714  2382.642857
73         3          18.000000     70.000000  2124.000000
           4          22.727273    109.272727  2338.090909
74         4          27.800000     96.533333  2151.466667
75         4          25.250000    114.833333  2489.250000
76         4          26.766667    106.333333  2306.600000
77         3          21.500000     80.000000  2720.000000
           4          29.107143    106.500000  2205.071429

# Индексирование с помощью иерархического индекса

Документация: https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html

In [20]:
year_cyl.head()

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
71         4          27.461538    101.846154  2056.384615     16.961538
           6          18.000000    243.375000  3171.875000     14.750000

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
           8          1.000000
71         4          1.923077
           6          1.000000

## Получаем данные на основе внешнего индекса

In [21]:
year_cyl.loc[70]

                 mpg  displacement       weight  acceleration    origin
cylinders
4          25.285714    107.000000  2292.571429     16.000000  2.285714
6          20.500000    199.000000  2710.500000     15.500000  1.000000
8          14.111111    367.555556  3940.055556     11.194444  1.000000

In [ ]:
year_cyl.loc[[70, 72]]

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
72         3          19.000000     70.000000  2330.000000     13.500000
           4          23.428571    111.535714  2382.642857     17.214286
           8          13.615385    344.846154  4228.384615     13.000000

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
           8          1.000000
72         3          3.000000
           4          1.928571
           8          1.000000

## Получаем одну строку

In [ ]:
year_cyl.loc[(70, 8)]

mpg               14.111111
displacement     367.555556
weight          3940.055556
acceleration      11.194444
origin             1.000000
Name: (70, 8), dtype: float64

# Получаем данные на основе пересечения (cross-section) с помощью .xs()

Этот метод использует параметр `key` для выборки данных на некотором уровне мульти-индекса.

## Параметры

    key : метка (label) или кортеж из меток
        Метка должна содержаться в индексе, или частично в мульти-индексе.
    axis : {0 или 'index', 1 или 'columns'}, по умолчанию 0
        Ось, по которой делаем пересечение.
    level : объект, по умолчанию первые n уровней (n=1 или len(key))
        В случае, если ключ частично содержится в мульти-индексе, то этот параметр указывает на те
        уровни, которые следует использовать. Уровни можно указывать с помощью меток или позиции.

In [ ]:
year_cyl.xs(key=70, axis=0, level='model_year')

                 mpg  displacement       weight  acceleration    origin
cylinders
4          25.285714    107.000000  2292.571429     16.000000  2.285714
6          20.500000    199.000000  2710.500000     15.500000  1.000000
8          14.111111    367.555556  3940.055556     11.194444  1.000000

In [ ]:
# Средние значения для 4 цилиндров по годам
year_cyl.xs(key=4, axis=0, level='cylinders')

                  mpg  displacement       weight  acceleration    origin
model_year
70          25.285714    107.000000  2292.571429     16.000000  2.285714
71          27.461538    101.846154  2056.384615     16.961538  1.923077
72          23.428571    111.535714  2382.642857     17.214286  1.928571
73          22.727273    109.272727  2338.090909     17.136364  2.000000
74          27.800000     96.533333  2151.466667     16.400000  2.200000
75          25.250000    114.833333  2489.250000     15.833333  2.166667
76          26.766667    106.333333  2306.600000     16.866667  1.866667
77          29.107143    106.500000  2205.071429     16.064286  1.857143
78          29.576471    112.117647  2296.764706     16.282353  2.117647
79          31.525000    113.583333  2357.583333     15.991667  1.583333
80          34.612000    111.000000  2360.080000     17.144000  2.200000
81          32.814286    108.857143  2275.476190     16.466667  2.095238
82          32.071429    118.571429  2402.321429     16.703571  1.714286

### Обратите внимание!

Имейте ввиду, что обычно гораздо проще отфильтровать данные **перед** вызовом функции groupby(), чем после. Например, намного проще удалить строки со значениями **cylinder=4** перед вызовом groupby(), а после это сделать уже сложнее.

In [ ]:
# ВНИМАНИЕ! В будущих версиях Scikit-Learn нужно добавлять параметр numeric_only=True
#
# df[df['cylinders'].isin([6,8])].groupby(['model_year','cylinders']).mean()

df[df['cylinders'].isin([6, 8])].groupby(
    ['model_year', 'cylinders']).mean(numeric_only=True)

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
71         6          18.000000    243.375000  3171.875000     14.750000
           8          13.428571    371.714286  4537.714286     12.214286
72         8          13.615385    344.846154  4228.384615     13.000000
73         6          19.000000    212.250000  2917.125000     15.687500
           8          13.200000    365.250000  4279.050000     12.250000
74         6          17.857143    230.428571  3320.000000     16.857143
           8          14.200000    315.200000  4438.400000     14.700000
75         6          17.583333    233.750000  3398.333333     17.708333
           8          15.666667    330.500000  4108.833333     13.166667
76         6          20.000000    221.400000  3349.600000     17.000000
           8          14.666667    324.000000  4064.666667     13.222222
77         6          19.500000    220.400000  3383.000000     16.900000
           8          16.000000    335.750000  4177.500000     13.662500
78         6          19.066667    213.250000  3314.166667     16.391667
           8          19.050000    300.833333  3563.333333     13.266667
79         6          22.950000    205.666667  3025.833333     15.433333
           8          18.630000    321.400000  3862.900000     15.400000
80         6          25.900000    196.500000  3145.500000     15.050000
81         6          23.428571    184.000000  3093.571429     15.442857
           8          26.600000    350.000000  3725.000000     19.000000
82         6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         6          1.000000
           8          1.000000
71         6          1.000000
           8          1.000000
72         8          1.000000
73         6          1.250000
           8          1.000000
74         6          1.000000
           8          1.000000
75         6          1.000000
           8          1.000000
76         6          1.300000
           8          1.000000
77         6          1.400000
           8          1.000000
78         6          1.166667
           8          1.000000
79         6          1.000000
           8          1.000000
80         6          2.000000
81         6          1.714286
           8          1.000000
82         6          1.000000

## Поменять уровни местами

- Как поменять уровни местами: https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html#swapping-levels-with-swaplevel
- Общий метод по изменению порядка уровней: https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html#reordering-levels-with-reorder-levels

In [27]:
year_cyl.swaplevel().head()

,,mpg,displacement,weight,acceleration,origin
cylinders,model_year,,,,,
4,70,25.285714,107.000000,2292.571429,16.000000,2.285714
6,70,20.500000,199.000000,2710.500000,15.500000,1.000000
8,70,14.111111,367.555556,3940.055556,11.194444,1.000000
4,71,27.461538,101.846154,2056.384615,16.961538,1.923077
6,71,18.000000,243.375000,3171.875000,14.750000,1.000000

## Сортировка мульти-индекса

- https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html#sorting-a-multiindex

In [ ]:
year_cyl.sort_index(level='model_year', ascending=False)

                            mpg  displacement       weight  acceleration  \
model_year cylinders
82         6          28.333333    225.000000  2931.666667     16.033333
           4          32.071429    118.571429  2402.321429     16.703571
81         8          26.600000    350.000000  3725.000000     19.000000
           6          23.428571    184.000000  3093.571429     15.442857
           4          32.814286    108.857143  2275.476190     16.466667
80         6          25.900000    196.500000  3145.500000     15.050000
           5          36.400000    121.000000  2950.000000     19.900000
           4          34.612000    111.000000  2360.080000     17.144000
           3          23.700000     70.000000  2420.000000     12.500000
79         8          18.630000    321.400000  3862.900000     15.400000
           6          22.950000    205.666667  3025.833333     15.433333
           5          25.400000    183.000000  3530.000000     20.100000
           4          31.525000    113.583333  2357.583333     15.991667
78         8          19.050000    300.833333  3563.333333     13.266667
           6          19.066667    213.250000  3314.166667     16.391667
           5          20.300000    131.000000  2830.000000     15.900000
           4          29.576471    112.117647  2296.764706     16.282353
77         8          16.000000    335.750000  4177.500000     13.662500
           6          19.500000    220.400000  3383.000000     16.900000
           4          29.107143    106.500000  2205.071429     16.064286
           3          21.500000     80.000000  2720.000000     13.500000
76         8          14.666667    324.000000  4064.666667     13.222222
           6          20.000000    221.400000  3349.600000     17.000000
           4          26.766667    106.333333  2306.600000     16.866667
75         8          15.666667    330.500000  4108.833333     13.166667
           6          17.583333    233.750000  3398.333333     17.708333
           4          25.250000    114.833333  2489.250000     15.833333
74         8          14.200000    315.200000  4438.400000     14.700000
           6          17.857143    230.428571  3320.000000     16.857143
           4          27.800000     96.533333  2151.466667     16.400000
73         8          13.200000    365.250000  4279.050000     12.250000
           6          19.000000    212.250000  2917.125000     15.687500
           4          22.727273    109.272727  2338.090909     17.136364
           3          18.000000     70.000000  2124.000000     13.500000
72         8          13.615385    344.846154  4228.384615     13.000000
           4          23.428571    111.535714  2382.642857     17.214286
           3          19.000000     70.000000  2330.000000     13.500000
71         8          13.428571    371.714286  4537.714286     12.214286
           6          18.000000    243.375000  3171.875000     14.750000
           4          27.461538    101.846154  2056.384615     16.961538
70         8          14.111111    367.555556  3940.055556     11.194444
           6          20.500000    199.000000  2710.500000     15.500000
           4          25.285714    107.000000  2292.571429     16.000000

                        origin
model_year cylinders
82         6          1.000000
           4          1.714286
81         8          1.000000
           6          1.714286
           4          2.095238
80         6          2.000000
           5          2.000000
           4          2.200000
           3          3.000000
79         8          1.000000
           6          1.000000
           5          2.000000
           4          1.583333
78         8          1.000000
           6          1.166667
           5          2.000000
           4          2.117647
77         8          1.000000
           6          1.400000
           4          1.857143
           3          3.000000
76         8          1.000000
           6          1.300000
           4          1.866667
75         8          1.000000
           6          1.000000
           4          2.166667
74         8          1.000000
           6          1.000000
           4          2.200000
73         8          1.000000
           6          1.250000
           4          2.000000
           3          3.000000
72         8          1.000000
           4          1.928571
           3          3.000000
71         8          1.000000
           6          1.000000
           4          1.923077
70         8          1.000000
           6          1.000000
           4          2.285714

In [ ]:
year_cyl.sort_index(level='cylinders', ascending=False)

,,mpg,displacement,weight,acceleration,origin
model_year,cylinders,,,,,
81,8,26.600000,350.000000,3725.000000,19.000000,1.000000
79,8,18.630000,321.400000,3862.900000,15.400000,1.000000
78,8,19.050000,300.833333,3563.333333,13.266667,1.000000
77,8,16.000000,335.750000,4177.500000,13.662500,1.000000
76,8,14.666667,324.000000,4064.666667,13.222222,1.000000
75,8,15.666667,330.500000,4108.833333,13.166667,1.000000
74,8,14.200000,315.200000,4438.400000,14.700000,1.000000
73,8,13.200000,365.250000,4279.050000,12.250000,1.000000
72,8,13.615385,344.846154,4228.384615,13.000000,1.000000
71,8,13.428571,371.714286,4537.714286,12.214286,1.000000
70,8,14.111111,367.555556,3940.055556,11.194444,1.000000
82,6,28.333333,225.000000,2931.666667,16.033333,1.000000
81,6,23.428571,184.000000,3093.571429,15.442857,1.714286
80,6,25.900000,196.500000,3145.500000,15.050000,2.000000
79,6,22.950000,205.666667,3025.833333,15.433333,1.000000
78,6,19.066667,213.250000,3314.166667,16.391667,1.166667
77,6,19.500000,220.400000,3383.000000,16.900000,1.400000
76,6,20.000000,221.400000,3349.600000,17.000000,1.300000
75,6,17.583333,233.750000,3398.333333,17.708333,1.000000
74,6,17.857143,230.428571,3320.000000,16.857143,1.000000
73,6,19.000000,212.250000,2917.125000,15.687500,1.250000
71,6,18.000000,243.375000,3171.875000,14.750000,1.000000
70,6,20.500000,199.000000,2710.500000,15.500000,1.000000
80,5,36.400000,121.000000,2950.000000,19.900000,2.000000
79,5,25.400000,183.000000,3530.000000,20.100000,2.000000
78,5,20.300000,131.000000,2830.000000,15.900000,2.000000
82,4,32.071429,118.571429,2402.321429,16.703571,1.714286
81,4,32.814286,108.857143,2275.476190,16.466667,2.095238
80,4,34.612000,111.000000,2360.080000,17.144000,2.200000
79,4,31.525000,113.583333,2357.583333,15.991667,1.583333
78,4,29.576471,112.117647,2296.764706,16.282353,2.117647
77,4,29.107143,106.500000,2205.071429,16.064286,1.857143
76,4,26.766667,106.333333,2306.600000,16.866667,1.866667
75,4,25.250000,114.833333,2489.250000,15.833333,2.166667
74,4,27.800000,96.533333,2151.466667,16.400000,2.200000
73,4,22.727273,109.272727,2338.090909,17.136364,2.000000
72,4,23.428571,111.535714,2382.642857,17.214286,1.928571
71,4,27.461538,101.846154,2056.384615,16.961538,1.923077
70,4,25.285714,107.000000,2292.571429,16.000000,2.285714
80,3,23.700000,70.000000,2420.000000,12.500000,3.000000
77,3,21.500000,80.000000,2720.000000,13.500000,3.000000
73,3,18.000000,70.000000,2124.000000,13.500000,3.000000
72,3,19.000000,70.000000,2330.000000,13.500000,3.000000

# Дополнительные материалы: метод agg()

Метод agg() позволяет Вам явно указать, какие именно методы агрегации следует использовать для каждой из категорий.

In [30]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

## agg() для DataFrame

In [ ]:
# Эти строковые значения должны совпадать со встроенными названиями методов агрегации

# ВНИМАНИЕ! В будущих версиях Scikit-Learn нужно будет отдельно выбирать
# только числовые колонки перед тем, как выполнять агрегацию.
# Это можно сделать по-разному, один из вариантов - использовать select_dtypes(include=[np.number])
#
# df.select_dtypes(include=[np.number]).agg(['median','mean'])

df.agg(['median', 'mean'])

,mpg,cylinders,displacement,weight,acceleration,model_year,origin
median,23.000000,4.000000,148.500000,2803.500000,15.50000,76.00000,1.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.56809,76.01005,1.572864

In [ ]:
# ВНИМАНИЕ! В будущих версиях Scikit-Learn нужно будет отдельно выбирать
# только числовые колонки перед тем, как выполнять агрегацию.
# Это можно сделать по-разному, один из вариантов - использовать select_dtypes(include=[np.number])
#
# df.select_dtypes(include=[np.number]).agg(['sum','mean'])[['mpg','weight']]

df.agg(['sum', 'mean'])[['mpg', 'weight']]

              mpg        weight
sum   9358.800000  1.182229e+06
mean    23.514573  2.970425e+03

### Указываем методы агрегации для колонок

**agg()** позволяет Вам передавать словарь, в котором ключи словаря это названия колонок, а значения словаря это методы агрегации для этих колонок.

In [ ]:
df.agg({'mpg': ['median', 'mean'], 'weight': ['mean', 'std']})

              mpg       weight
mean    23.514573  2970.424623
median  23.000000          NaN
std           NaN   846.841774

## agg() с groupby()

In [ ]:
df.groupby('model_year').agg(
    {'mpg': ['median', 'mean'], 'weight': ['mean', 'std']})

              mpg                  weight
           median       mean         mean          std
model_year
70          16.00  17.689655  3372.793103   852.868663
71          19.00  21.250000  2995.428571  1061.830859
72          18.50  18.714286  3237.714286   974.520960
73          16.00  17.100000  3419.025000   974.809133
74          24.00  22.703704  2877.925926   949.308571
75          19.50  20.266667  3176.800000   765.179781
76          21.00  21.573529  3078.735294   821.371481
77          21.75  23.375000  2997.357143   912.825902
78          20.70  24.061111  2861.805556   626.023907
79          23.90  25.093103  3055.344828   747.881497
80          32.70  33.696552  2436.655172   432.235491
81          31.60  30.334483  2522.931034   533.600501
82          32.00  31.709677  2453.548387   354.276713

# Мои дополнения

In [ ]:
# тесты с индексом
# year_cyl.loc[70:77] # можно выбирать срезы по первому индексу
idx = pd.IndexSlice
# таким способом возьмём нужные из мультииндекса и все стобцы
year_cyl.loc[idx[70:77, 3:5], :]
# таким способом возьмём нужные из мультииндекса и все стобцы
year_cyl.loc[idx[70:77, 3:5], 'mpg':'weight']

                            mpg  displacement       weight
model_year cylinders
70         4          25.285714    107.000000  2292.571429
71         4          27.461538    101.846154  2056.384615
72         3          19.000000     70.000000  2330.000000
           4          23.428571    111.535714  2382.642857
73         3          18.000000     70.000000  2124.000000
           4          22.727273    109.272727  2338.090909
74         4          27.800000     96.533333  2151.466667
75         4          25.250000    114.833333  2489.250000
76         4          26.766667    106.333333  2306.600000
77         3          21.500000     80.000000  2720.000000
           4          29.107143    106.500000  2205.071429

In [21]:
# важен порядок передачи стольцеов для группировки для группировки
display(df.groupby(['cylinders', 'model_year']).mean(numeric_only=True))
display(df.groupby(['model_year', 'cylinders']).mean(numeric_only=True))

                            mpg  displacement       weight  acceleration  \
cylinders model_year
3         72          19.000000     70.000000  2330.000000     13.500000
          73          18.000000     70.000000  2124.000000     13.500000
          77          21.500000     80.000000  2720.000000     13.500000
          80          23.700000     70.000000  2420.000000     12.500000
4         70          25.285714    107.000000  2292.571429     16.000000
          71          27.461538    101.846154  2056.384615     16.961538
          72          23.428571    111.535714  2382.642857     17.214286
          73          22.727273    109.272727  2338.090909     17.136364
          74          27.800000     96.533333  2151.466667     16.400000
          75          25.250000    114.833333  2489.250000     15.833333
          76          26.766667    106.333333  2306.600000     16.866667
          77          29.107143    106.500000  2205.071429     16.064286
          78          29.576471    112.117647  2296.764706     16.282353
          79          31.525000    113.583333  2357.583333     15.991667
          80          34.612000    111.000000  2360.080000     17.144000
          81          32.814286    108.857143  2275.476190     16.466667
          82          32.071429    118.571429  2402.321429     16.703571
5         78          20.300000    131.000000  2830.000000     15.900000
          79          25.400000    183.000000  3530.000000     20.100000
          80          36.400000    121.000000  2950.000000     19.900000
6         70          20.500000    199.000000  2710.500000     15.500000
          71          18.000000    243.375000  3171.875000     14.750000
          73          19.000000    212.250000  2917.125000     15.687500
          74          17.857143    230.428571  3320.000000     16.857143
          75          17.583333    233.750000  3398.333333     17.708333
          76          20.000000    221.400000  3349.600000     17.000000
          77          19.500000    220.400000  3383.000000     16.900000
          78          19.066667    213.250000  3314.166667     16.391667
          79          22.950000    205.666667  3025.833333     15.433333
          80          25.900000    196.500000  3145.500000     15.050000
          81          23.428571    184.000000  3093.571429     15.442857
          82          28.333333    225.000000  2931.666667     16.033333
8         70          14.111111    367.555556  3940.055556     11.194444
          71          13.428571    371.714286  4537.714286     12.214286
          72          13.615385    344.846154  4228.384615     13.000000
          73          13.200000    365.250000  4279.050000     12.250000
          74          14.200000    315.200000  4438.400000     14.700000
          75          15.666667    330.500000  4108.833333     13.166667
          76          14.666667    324.000000  4064.666667     13.222222
          77          16.000000    335.750000  4177.500000     13.662500
          78          19.050000    300.833333  3563.333333     13.266667
          79          18.630000    321.400000  3862.900000     15.400000
          81          26.600000    350.000000  3725.000000     19.000000

                        origin
cylinders model_year
3         72          3.000000
          73          3.000000
          77          3.000000
          80          3.000000
4         70          2.285714
          71          1.923077
          72          1.928571
          73          2.000000
          74          2.200000
          75          2.166667
          76          1.866667
          77          1.857143
          78          2.117647
          79          1.583333
          80          2.200000
          81          2.095238
          82          1.714286
5         78          2.000000
          79          2.000000
          80          2.000000
6         70          1.000000
          71          1.000000
          73          1.250000
          74          1.000000
          75          1.000000
          76          1.300000
          77          1.400000
          78          1.166667
          79          1.000000
          80          2.000000
          81          1.714286
          82          1.000000
8         70          1.000000
          71          1.000000
          72          1.000000
          73          1.000000
          74          1.000000
          75          1.000000
          76          1.000000
          77          1.000000
          78          1.000000
          79          1.000000
          81          1.000000

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
71         4          27.461538    101.846154  2056.384615     16.961538
           6          18.000000    243.375000  3171.875000     14.750000
           8          13.428571    371.714286  4537.714286     12.214286
72         3          19.000000     70.000000  2330.000000     13.500000
           4          23.428571    111.535714  2382.642857     17.214286
           8          13.615385    344.846154  4228.384615     13.000000
73         3          18.000000     70.000000  2124.000000     13.500000
           4          22.727273    109.272727  2338.090909     17.136364
           6          19.000000    212.250000  2917.125000     15.687500
           8          13.200000    365.250000  4279.050000     12.250000
74         4          27.800000     96.533333  2151.466667     16.400000
           6          17.857143    230.428571  3320.000000     16.857143
           8          14.200000    315.200000  4438.400000     14.700000
75         4          25.250000    114.833333  2489.250000     15.833333
           6          17.583333    233.750000  3398.333333     17.708333
           8          15.666667    330.500000  4108.833333     13.166667
76         4          26.766667    106.333333  2306.600000     16.866667
           6          20.000000    221.400000  3349.600000     17.000000
           8          14.666667    324.000000  4064.666667     13.222222
77         3          21.500000     80.000000  2720.000000     13.500000
           4          29.107143    106.500000  2205.071429     16.064286
           6          19.500000    220.400000  3383.000000     16.900000
           8          16.000000    335.750000  4177.500000     13.662500
78         4          29.576471    112.117647  2296.764706     16.282353
           5          20.300000    131.000000  2830.000000     15.900000
           6          19.066667    213.250000  3314.166667     16.391667
           8          19.050000    300.833333  3563.333333     13.266667
79         4          31.525000    113.583333  2357.583333     15.991667
           5          25.400000    183.000000  3530.000000     20.100000
           6          22.950000    205.666667  3025.833333     15.433333
           8          18.630000    321.400000  3862.900000     15.400000
80         3          23.700000     70.000000  2420.000000     12.500000
           4          34.612000    111.000000  2360.080000     17.144000
           5          36.400000    121.000000  2950.000000     19.900000
           6          25.900000    196.500000  3145.500000     15.050000
81         4          32.814286    108.857143  2275.476190     16.466667
           6          23.428571    184.000000  3093.571429     15.442857
           8          26.600000    350.000000  3725.000000     19.000000
82         4          32.071429    118.571429  2402.321429     16.703571
           6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
           8          1.000000
71         4          1.923077
           6          1.000000
           8          1.000000
72         3          3.000000
           4          1.928571
           8          1.000000
73         3          3.000000
           4          2.000000
           6          1.250000
           8          1.000000
74         4          2.200000
           6          1.000000
           8          1.000000
75         4          2.166667
           6          1.000000
           8          1.000000
76         4          1.866667
           6          1.300000
           8          1.000000
77         3          3.000000
           4          1.857143
           6          1.400000
           8          1.000000
78         4          2.117647
           5          2.000000
           6          1.166667
           8          1.000000
79         4          1.583333
           5          2.000000
           6          1.000000
           8          1.000000
80         3          3.000000
           4          2.200000
           5          2.000000
           6          2.000000
81         4          2.095238
           6          1.714286
           8          1.000000
82         4          1.714286
           6          1.000000

In [23]:
df.head(3)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite

Если хочется применить функции агрегации к данным после агрегации,
то нужно учесть функции, работающие только с числовыми данными.
предварительно отсеять
df.select_dtypes(np.number) или df.select_dtypes(include=[np.number])
но возникает проблема, что группировочные колонки могут также не быть числовыми,
поэтому может пригодиться другой метод

`numeric_cols = df.select_dtypes(np.number).columns.difference(['model_year', 'cylinders'])
df.groupby(['model_year', 'cylinders'])[numeric_cols].agg(['std', 'mean'])`

т.е. взять эти колонки после агрегации

In [ ]:
display(df.select_dtypes(np.number).groupby(
    ['model_year', 'cylinders']).agg(['std', 'mean']))

In [ ]:
numeric_cols = df.select_dtypes(np.number).columns.difference([
    'model_year', 'cylinders'])
df.groupby(['model_year', 'cylinders'])[numeric_cols].agg(['std', 'mean'])

                     acceleration            displacement              \
                              std       mean          std        mean
model_year cylinders
70         4             2.661453  16.000000     8.660254  107.000000
           6             0.408248  15.500000     0.816497  199.000000
           8             2.668657  11.194444    59.076443  367.555556
71         4             2.536907  16.961538    23.053728  101.846154
           6             1.000000  14.750000    11.867573  243.375000
           8             0.755929  12.214286    32.438220  371.714286
72         3                  NaN  13.500000          NaN   70.000000
           4             2.423557  17.214286    14.167221  111.535714
           8             1.307032  13.000000    42.160104  344.846154
73         3                  NaN  13.500000          NaN   70.000000
           4             2.440194  17.136364    18.926653  109.272727
           6             1.462324  15.687500    38.614394  212.250000
           8             1.312892  12.250000    44.960655  365.250000
74         4             1.938335  16.400000    20.469024   96.533333
           6             0.626783  16.857143    24.275208  230.428571
           8             1.036822  14.700000    20.571825  315.200000
75         4             1.683251  15.833333    18.765700  114.833333
           6             2.250842  17.708333    22.875652  233.750000
           8             1.169045  13.166667    47.521574  330.500000
76         4             3.064699  16.866667    18.634326  106.333333
           6             1.814754  17.000000    35.774603  221.400000
           8             0.952336  13.222222    20.718349  324.000000
77         3                  NaN  13.500000          NaN   80.000000
           4             1.696878  16.064286    20.323348  106.500000
           6             1.662829  16.900000    43.073194  220.400000
           8             2.560657  13.662500    49.032788  335.750000
78         4             2.016877  16.282353    24.191637  112.117647
           5                  NaN  15.900000          NaN  131.000000
           6             1.842655  16.391667    28.844804  213.250000
           8             1.390923  13.266667    21.339322  300.833333
79         4             3.249464  15.991667    25.914048  113.583333
           5                  NaN  20.100000          NaN  183.000000
           6             2.834549  15.433333    27.840019  205.666667
           8             2.718251  15.400000    36.914917  321.400000
80         3                  NaN  12.500000          NaN   70.000000
           4             2.585388  17.144000    24.608603  111.000000
           5                  NaN  19.900000          NaN  121.000000
           6             5.161880  15.050000    40.305087  196.500000
81         4             2.015275  16.466667    23.007142  108.857143
           6             2.593490  15.442857    35.327043  184.000000
           8                  NaN  19.000000          NaN  350.000000
82         4             2.590364  16.703571    21.439715  118.571429
           6             1.193035  16.033333    40.951190  225.000000

                           mpg               origin                weight  \
                           std       mean       std      mean         std
model_year cylinders
70         4          1.112697  25.285714  0.487950  2.285714  263.055037
           6          1.732051  20.500000  0.000000  1.000000  112.837641
           8          2.609685  14.111111  0.000000  1.000000  496.964488
71         4          3.502746  27.461538  0.862316  1.923077  217.933300
           6          1.069045  18.000000  0.000000  1.000000  259.952434
           8          0.786796  13.428571  0.000000  1.000000  415.550524
72         3               NaN  19.000000       NaN  3.000000         NaN
           4          3.056249  23.428571  0.828742  1.928571  274.992477
           8          1.502135  13.615385  0.000000  1.000000  264.578765
73         3               NaN  18.000000       NaN  3.000000         NaN
           4          3.319365  22.727273  0.632456  2.000000  293.964098
           6          2.203893  19.000000  0.707107  1.250000  242.078758
           8          1.361114  13.200000  0.000000  1.000000  483.828751
74         4          2.932576  27.800000  0.774597  2.200000  257.012470
           6          2.267787  17.857143  0.000000  1.000000  369.025744
           8          1.095445  14.200000  0.000000  1.000000  239.505324
75         4          3.333712  25.250000  0.717741  2.166667  374.401613
           6          2.020726  17.583333  0.000000  1.000000  359.040219
           8          2.422120  15.666667  0.000000  1.000000  713.556001
76         4          3.825976  26.766667  0.743223  1.866667  436.720375
           6          2.494438  20.000000  0.674949  1.300000  306.941254
           8          1.767767  14.666667  0.000000  1.000000  200.096227
77         3               NaN  21.500000       NaN  3.000000         NaN
           4          4.039129  29.107143  0.864438  1.857143  298.321062
           6          1.767767  19.500000  0.894427  1.400000  325.703086
           8          0.845154  16.000000  0.000000  1.000000  154.017624
78         4          6.384799  29.576471  0.927520  2.117647  349.351816
           5               NaN  20.300000       NaN  2.000000         NaN
           6          1.548802  19.066667  0.389249  1.166667  200.814629
           8          1.048332  19.050000  0.000000  1.000000  310.912635
79         4          4.349739  31.525000  0.792961  1.583333  423.623001
           5               NaN  25.400000       NaN  2.000000         NaN
           6          3.851104  22.950000  0.000000  1.000000  319.365256
           8          2.757636  18.630000  0.000000  1.000000  254.455170
80         3               NaN  23.700000       NaN  3.000000         NaN
           4          6.597621  34.612000  0.816497  2.200000  392.902333
           5               NaN  36.400000       NaN  2.000000         NaN
           6          9.616652  25.900000  1.414214  2.000000  333.047294
81         4          3.844904  32.814286  0.943650  2.095238  354.629753
           6          4.139531  23.428571  0.951190  1.714286  272.911987
           8               NaN  26.600000       NaN  1.000000         NaN
82         4          5.054727  32.071429  0.937180  1.714286  332.756396
           6          8.504901  28.333333  0.000000  1.000000   90.737717


                             mean
model_year cylinders
70         4          2292.571429
           6          2710.500000
           8          3940.055556
71         4          2056.384615
           6          3171.875000
           8          4537.714286
72         3          2330.000000
           4          2382.642857
           8          4228.384615
73         3          2124.000000
           4          2338.090909
           6          2917.125000
           8          4279.050000
74         4          2151.466667
           6          3320.000000
           8          4438.400000
75         4          2489.250000
           6          3398.333333
           8          4108.833333
76         4          2306.600000
           6          3349.600000
           8          4064.666667
77         3          2720.000000
           4          2205.071429
           6          3383.000000
           8          4177.500000
78         4          2296.764706
           5          2830.000000
           6          3314.166667
           8          3563.333333
79         4          2357.583333
           5          3530.000000
           6          3025.833333
           8          3862.900000
80         3          2420.000000
           4          2360.080000
           5          2950.000000
           6          3145.500000
81         4          2275.476190
           6          3093.571429
           8          3725.000000
82         4          2402.321429
           6          2931.666667

In [ ]:
# колону можно переименовать
numeric_cols = df.select_dtypes(np.number).columns.difference([
    'model_year', 'cylinders'])
df.groupby(['model_year', 'cylinders'])[
    numeric_cols].agg([('отклонился', 'std'), 'mean'])

                     acceleration            displacement              \
                       отклонился       mean   отклонился        mean
model_year cylinders
70         4             2.661453  16.000000     8.660254  107.000000
           6             0.408248  15.500000     0.816497  199.000000
           8             2.668657  11.194444    59.076443  367.555556
71         4             2.536907  16.961538    23.053728  101.846154
           6             1.000000  14.750000    11.867573  243.375000
           8             0.755929  12.214286    32.438220  371.714286
72         3                  NaN  13.500000          NaN   70.000000
           4             2.423557  17.214286    14.167221  111.535714
           8             1.307032  13.000000    42.160104  344.846154
73         3                  NaN  13.500000          NaN   70.000000
           4             2.440194  17.136364    18.926653  109.272727
           6             1.462324  15.687500    38.614394  212.250000
           8             1.312892  12.250000    44.960655  365.250000
74         4             1.938335  16.400000    20.469024   96.533333
           6             0.626783  16.857143    24.275208  230.428571
           8             1.036822  14.700000    20.571825  315.200000
75         4             1.683251  15.833333    18.765700  114.833333
           6             2.250842  17.708333    22.875652  233.750000
           8             1.169045  13.166667    47.521574  330.500000
76         4             3.064699  16.866667    18.634326  106.333333
           6             1.814754  17.000000    35.774603  221.400000
           8             0.952336  13.222222    20.718349  324.000000
77         3                  NaN  13.500000          NaN   80.000000
           4             1.696878  16.064286    20.323348  106.500000
           6             1.662829  16.900000    43.073194  220.400000
           8             2.560657  13.662500    49.032788  335.750000
78         4             2.016877  16.282353    24.191637  112.117647
           5                  NaN  15.900000          NaN  131.000000
           6             1.842655  16.391667    28.844804  213.250000
           8             1.390923  13.266667    21.339322  300.833333
79         4             3.249464  15.991667    25.914048  113.583333
           5                  NaN  20.100000          NaN  183.000000
           6             2.834549  15.433333    27.840019  205.666667
           8             2.718251  15.400000    36.914917  321.400000
80         3                  NaN  12.500000          NaN   70.000000
           4             2.585388  17.144000    24.608603  111.000000
           5                  NaN  19.900000          NaN  121.000000
           6             5.161880  15.050000    40.305087  196.500000
81         4             2.015275  16.466667    23.007142  108.857143
           6             2.593490  15.442857    35.327043  184.000000
           8                  NaN  19.000000          NaN  350.000000
82         4             2.590364  16.703571    21.439715  118.571429
           6             1.193035  16.033333    40.951190  225.000000

                            mpg                origin                weight  \
                     отклонился       mean отклонился      mean  отклонился
model_year cylinders
70         4           1.112697  25.285714   0.487950  2.285714  263.055037
           6           1.732051  20.500000   0.000000  1.000000  112.837641
           8           2.609685  14.111111   0.000000  1.000000  496.964488
71         4           3.502746  27.461538   0.862316  1.923077  217.933300
           6           1.069045  18.000000   0.000000  1.000000  259.952434
           8           0.786796  13.428571   0.000000  1.000000  415.550524
72         3                NaN  19.000000        NaN  3.000000         NaN
           4           3.056249  23.428571   0.828742  1.928571  274.992477
           8           1.502135  13.615385   0.000000  1.000000  264.578765
73         3                NaN  18.000000        NaN  3.000000         NaN
           4           3.319365  22.727273   0.632456  2.000000  293.964098
           6           2.203893  19.000000   0.707107  1.250000  242.078758
           8           1.361114  13.200000   0.000000  1.000000  483.828751
74         4           2.932576  27.800000   0.774597  2.200000  257.012470
           6           2.267787  17.857143   0.000000  1.000000  369.025744
           8           1.095445  14.200000   0.000000  1.000000  239.505324
75         4           3.333712  25.250000   0.717741  2.166667  374.401613
           6           2.020726  17.583333   0.000000  1.000000  359.040219
           8           2.422120  15.666667   0.000000  1.000000  713.556001
76         4           3.825976  26.766667   0.743223  1.866667  436.720375
           6           2.494438  20.000000   0.674949  1.300000  306.941254
           8           1.767767  14.666667   0.000000  1.000000  200.096227
77         3                NaN  21.500000        NaN  3.000000         NaN
           4           4.039129  29.107143   0.864438  1.857143  298.321062
           6           1.767767  19.500000   0.894427  1.400000  325.703086
           8           0.845154  16.000000   0.000000  1.000000  154.017624
78         4           6.384799  29.576471   0.927520  2.117647  349.351816
           5                NaN  20.300000        NaN  2.000000         NaN
           6           1.548802  19.066667   0.389249  1.166667  200.814629
           8           1.048332  19.050000   0.000000  1.000000  310.912635
79         4           4.349739  31.525000   0.792961  1.583333  423.623001
           5                NaN  25.400000        NaN  2.000000         NaN
           6           3.851104  22.950000   0.000000  1.000000  319.365256
           8           2.757636  18.630000   0.000000  1.000000  254.455170
80         3                NaN  23.700000        NaN  3.000000         NaN
           4           6.597621  34.612000   0.816497  2.200000  392.902333
           5                NaN  36.400000        NaN  2.000000         NaN
           6           9.616652  25.900000   1.414214  2.000000  333.047294
81         4           3.844904  32.814286   0.943650  2.095238  354.629753
           6           4.139531  23.428571   0.951190  1.714286  272.911987
           8                NaN  26.600000        NaN  1.000000         NaN
82         4           5.054727  32.071429   0.937180  1.714286  332.756396
           6           8.504901  28.333333   0.000000  1.000000   90.737717


                             mean
model_year cylinders
70         4          2292.571429
           6          2710.500000
           8          3940.055556
71         4          2056.384615
           6          3171.875000
           8          4537.714286
72         3          2330.000000
           4          2382.642857
           8          4228.384615
73         3          2124.000000
           4          2338.090909
           6          2917.125000
           8          4279.050000
74         4          2151.466667
           6          3320.000000
           8          4438.400000
75         4          2489.250000
           6          3398.333333
           8          4108.833333
76         4          2306.600000
           6          3349.600000
           8          4064.666667
77         3          2720.000000
           4          2205.071429
           6          3383.000000
           8          4177.500000
78         4          2296.764706
           5          2830.000000
           6          3314.166667
           8          3563.333333
79         4          2357.583333
           5          3530.000000
           6          3025.833333
           8          3862.900000
80         3          2420.000000
           4          2360.080000
           5          2950.000000
           6          3145.500000
81         4          2275.476190
           6          3093.571429
           8          3725.000000
82         4          2402.321429
           6          2931.666667

In [ ]:
# указание функций агрегации для голонок
numeric_cols = df.select_dtypes(np.number).columns.difference(
    ['model_year', 'cylinders'])
print(numeric_cols)
df.groupby(['model_year', 'cylinders'])[numeric_cols].agg(mpg_std=('mpg', 'std'),
                                                          mpg_mean=(
                                                              'mpg', 'mean'),
                                                          displacement_std=(
                                                              'displacement', 'std'),
                                                          weight_mean=('weight', 'mean'))

In [ ]:
# указание функций агрегации для голонок
numeric_cols = df.select_dtypes(np.number).columns.difference(
    ['model_year', 'cylinders'])
print(numeric_cols)
df.groupby(['model_year', 'cylinders'])[
    numeric_cols].agg({'mpg': ['max', 'min'], 'weight': 'mean'})

Index(['acceleration', 'displacement', 'mpg', 'origin', 'weight'], dtype='object')

                       mpg             weight
                       max   min         mean
model_year cylinders
70         4          27.0  24.0  2292.571429
           6          22.0  18.0  2710.500000
           8          18.0   9.0  3940.055556
71         4          35.0  22.0  2056.384615
           6          19.0  16.0  3171.875000
           8          14.0  12.0  4537.714286
72         3          19.0  19.0  2330.000000
           4          28.0  18.0  2382.642857
           8          17.0  11.0  4228.384615
73         3          18.0  18.0  2124.000000
           4          29.0  19.0  2338.090909
           6          23.0  16.0  2917.125000
           8          16.0  11.0  4279.050000
74         4          32.0  24.0  2151.466667
           6          21.0  15.0  3320.000000
           8          16.0  13.0  4438.400000
75         4          33.0  22.0  2489.250000
           6          21.0  15.0  3398.333333
           8          20.0  13.0  4108.833333
76         4          33.0  19.0  2306.600000
           6          24.0  16.5  3349.600000
           8          17.5  13.0  4064.666667
77         3          21.5  21.5  2720.000000
           4          36.0  21.5  2205.071429
           6          22.0  17.5  3383.000000
           8          17.5  15.0  4177.500000
78         4          43.1  21.1  2296.764706
           5          20.3  20.3  2830.000000
           6          20.8  16.2  3314.166667
           8          20.2  17.5  3563.333333
79         4          37.3  22.3  2357.583333
           5          25.4  25.4  3530.000000
           6          28.8  19.8  3025.833333
           8          23.9  15.5  3862.900000
80         3          23.7  23.7  2420.000000
           4          46.6  23.6  2360.080000
           5          36.4  36.4  2950.000000
           6          32.7  19.1  3145.500000
81         4          39.1  25.8  2275.476190
           6          30.7  17.6  3093.571429
           8          26.6  26.6  3725.000000
82         4          44.0  23.0  2402.321429
           6          38.0  22.0  2931.666667

In [47]:
# без группировки агрегирующие функции применяются ко всему

numeric_cols = df.select_dtypes(np.number).columns.difference(
    ['model_year', 'cylinders'])
print(numeric_cols)
df[numeric_cols].agg({'mpg': ['max', 'min'], 'weight': 'mean'})

Index(['acceleration', 'displacement', 'mpg', 'origin', 'weight'], dtype='object')

       mpg       weight
max   46.6          NaN
min    9.0          NaN
mean   NaN  2970.424623